//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Squadly
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projects
    {
        public int project_id { get; set; }
        public string project_name { get; set; }
        public string description { get; set; }
        public System.DateTime created_at { get; set; }
    }
}
